<template>
  <el-dialog title="查询银行编号" v-model="isVisible" :show-close="false">
    <el-button type="text" class="el-icon-close" @click.native="closeDialog"></el-button>
    <el-form ref="ruleForm" label-width="150px">
      <el-input v-model="searchValue" @click.native="handleInput" placeholder="银行名称/编号" style="width: 300px; margin-left: auto; margin-right: auto; margin-bottom: 20px;">
        <el-button slot="append" icon="search" @click.native="search"></el-button>
      </el-input>
      <el-table
        :data="result"
        border
        height="400"
        style="width: 100%">
        <!-- <el-table-column type="index" width="50" label="序号"></el-table-column> -->
        <el-table-column
          property="index"
          label="序号"
          width="180">
        </el-table-column>
        <el-table-column
          property="name"
          label="银行名称"
          width="180">
        </el-table-column>
        <el-table-column
          property="code"
          label="银行编码">
        </el-table-column>
      </el-table>
    </el-form>
  </el-dialog>
</template>
<style scoped>
.el-icon-close{
  cursor: pointer;
  position: fixed;
  top: 1%;
  right: 2%;
}
</style>
<script>
  export default {
    props: ['bankVisible'],
    data() {
      return {
        searchValue: '',
        result: [],
        tableData: [{
          index: '1',
          name: '中国银行',
          code: 'BOC'
        }, {
          index: '2',
          name: '工商银行',
          code: 'ICBC'
        }, {
          index: '3',
          name: '建设银行',
          code: 'CCB'
        }, {
          index: '4',
          name: '交通银行',
          code: 'COMM'
        }, {
          index: '5',
          name: '华夏银行',
          code: 'HXB'
        }, {
          index: '6',
          name: '招商银行',
          code: 'CMB'
        }, {
          index: '7',
          name: '光大银行',
          code: 'CEB'
        }, {
          index: '8',
          name: '农业银行',
          code: 'ABC'
        }, {
          index: '9',
          name: '民生银行',
          code: 'CMBC'
        }, {
          index: '10',
          name: '兴业银行',
          code: 'CIB'
        }, {
          index: '11',
          name: '中信银行',
          code: 'CITIC'
        }, {
          index: '12',
          name: '北京银行',
          code: 'BJB'
        }, {
          index: '13',
          name: '浦发银行',
          code: 'SPDB'
        }, {
          index: '14',
          name: '上海银行',
          code: 'BOSH'
        }, {
          index: '15',
          name: '平安银行',
          code: 'PAB'
        }, {
          index: '16',
          name: '邮政储蓄银行',
          code: 'PSBC'
        }, {
          index: '17',
          name: '恒丰银行',
          code: 'EGB'
        }, {
          index: '18',
          name: '花旗银行',
          code: 'CITIBANK'
        }, {
          index: '19',
          name: '浙商银行',
          code: 'CZB'
        }, {
          index: '20',
          name: '渤海银行',
          code: 'CBHB'
        }, {
          index: '21',
          name: '邢台银行',
          code: 'XTB'
        }, {
          index: '22',
          name: '张家口市商业银行',
          code: 'ZJKCCB'
        }, {
          index: '23',
          name: '承德银行',
          code: 'BOCD'
        }, {
          index: '24',
          name: '沧州银行',
          code: 'BOCZ'
        }, {
          index: '25',
          name: '晋商银行',
          code: 'BOJS'
        }, {
          index: '26',
          name: '晋城市商业银行',
          code: 'JCB'
        }, {
          index: '27',
          name: '内蒙古银行',
          code: 'BOIM'
        }, {
          index: '28',
          name: '包商银行',
          code: 'BSB'
        }, {
          index: '29',
          name: '鄂尔多斯银行',
          code: 'ORDOSB'
        }, {
          index: '30',
          name: '大连银行',
          code: 'DLB'
        }, {
          index: '31',
          name: '鞍山市商业银行',
          code: 'BOAS'
        }, {
          index: '32',
          name: '锦州银行',
          code: 'BOJZ'
        }, {
          index: '33',
          name: '葫芦岛银行',
          code: 'BOHL'
        }, {
          index: '34',
          name: '营口银行',
          code: 'BOYK'
        }, {
          index: '35',
          name: '阜新银行',
          code: 'BOFX'
        }, {
          index: '36',
          name: '吉林银行',
          code: 'BOJL'
        }, {
          index: '37',
          name: '哈尔滨银行',
          code: 'HRBCB'
        }, {
          index: '38',
          name: '龙江银行',
          code: 'LJB'
        }, {
          index: '39',
          name: '南京银行',
          code: 'NJCB'
        }, {
          index: '40',
          name: '江苏银行',
          code: 'JSBC'
        }, {
          index: '41',
          name: '杭州银行',
          code: 'HZCB'
        }, {
          index: '42',
          name: '宁波银行',
          code: 'NBCB'
        }, {
          index: '43',
          name: '温州银行',
          code: 'WZCB'
        }, {
          index: '44',
          name: '湖州银行',
          code: 'BOHZ'
        }, {
          index: '45',
          name: '绍兴银行',
          code: 'BOSX'
        }, {
          index: '46',
          name: '浙江稠州商业银行',
          code: 'CZCB'
        }, {
          index: '47',
          name: '台州银行',
          code: 'TZB'
        }, {
          index: '48',
          name: '浙江泰隆商业银行',
          code: 'ZJTLCB'
        }, {
          index: '49',
          name: '浙江民泰商业银行',
          code: 'MTCB'
        }, {
          index: '50',
          name: '福建海峡银行',
          code: 'FHB'
        }, {
          index: '51',
          name: '厦门银行',
          code: 'XMCCB'
        }, {
          index: '52',
          name: '南昌银行',
          code: 'NCB'
        }, {
          index: '53',
          name: '赣州银行',
          code: 'GZBANK'
        }, {
          index: '54',
          name: '上饶银行',
          code: 'SRB'
        }, {
          index: '55',
          name: '青岛银行',
          code: 'QDCCB'
        }, {
          index: '56',
          name: '齐商银行',
          code: 'QSB'
        }, {
          index: '57',
          name: '东营市商业银行',
          code: 'DYCCB'
        }, {
          index: '58',
          name: '烟台银行',
          code: 'YTB'
        }, {
          index: '59',
          name: '潍坊银行',
          code: 'BOWF'
        }, {
          index: '60',
          name: '济宁银行',
          code: 'BOJN'
        }, {
          index: '61',
          name: '泰安市商业银行',
          code: 'TACCB'
        }, {
          index: '62',
          name: '莱商银行',
          code: 'LSB'
        }, {
          index: '63',
          name: '威海市商业银行',
          code: 'WHCCB'
        }, {
          index: '64',
          name: '德州银行',
          code: 'DZB'
        }, {
          index: '65',
          name: '临商银行',
          code: 'BOLS'
        }, {
          index: '66',
          name: '日照银行',
          code: 'BORZ'
        }, {
          index: '67',
          name: '郑州银行',
          code: 'BOZZ'
        }, {
          index: '68',
          name: '洛阳银行',
          code: 'BOLY'
        }, {
          index: '69',
          name: '漯河市商业银行',
          code: 'BOLH'
        }, {
          index: '70',
          name: '中原银行',
          code: 'ZYB'
        }, {
          index: '71',
          name: '汉口银行',
          code: 'HKB'
        }, {
          index: '72',
          name: '长沙银行',
          code: 'CSCB'
        }, {
          index: '73',
          name: '广州银行',
          code: 'GZB'
        }, {
          index: '74',
          name: '深圳发展银行',
          code: 'SZDB'
        }, {
          index: '75',
          name: '东莞银行',
          code: 'BODG'
        }, {
          index: '76',
          name: '广西北部湾银行',
          code: 'GBGB'
        }, {
          index: '77',
          name: '柳州银行',
          code: 'BOLZ'
        }, {
          index: '78',
          name: '重庆银行',
          code: 'CQCB'
        }, {
          index: '79',
          name: '攀枝花市商业银行',
          code: 'PCCB'
        }, {
          index: '80',
          name: '德阳银行',
          code: 'BODY'
        }, {
          index: '81',
          name: '绵阳市商业银行',
          code: 'MYCCB'
        }, {
          index: '82',
          name: '贵阳市商业银行',
          code: 'GYCB'
        }, {
          index: '83',
          name: '富滇银行',
          code: 'FDB'
        }, {
          index: '84',
          name: '兰州银行',
          code: 'LZYH'
        }, {
          index: '85',
          name: '青海银行',
          code: 'BOQH'
        }, {
          index: '86',
          name: '宁夏银行',
          code: 'BONX'
        }, {
          index: '87',
          name: '乌鲁木齐市商业银行',
          code: 'UCCB'
        }, {
          index: '88',
          name: '昆仑银行',
          code: 'BOK'
        }, {
          index: '89',
          name: '苏州银行',
          code: 'BOSZ'
        }, {
          index: '90',
          name: '昆山农村商业银行',
          code: 'KSNX'
        }, {
          index: '91',
          name: '吴江农村商业银行',
          code: 'WJRCB'
        }, {
          index: '92',
          name: '江苏常熟农村商业银行',
          code: 'CSRCB'
        }, {
          index: '93',
          name: '张家港农村商业银行',
          code: 'RCBOZ'
        }, {
          index: '94',
          name: '广州农村商业银行',
          code: 'GRCB'
        }, {
          index: '95',
          name: '佛山顺德农村商业银行',
          code: 'SDEB'
        }, {
          index: '96',
          name: '重庆农村商业银行',
          code: 'CQRCB'
        }, {
          index: '97',
          name: '其他',
          code: 'QTB'
        }, {
          index: '98',
          name: '广东发展银行',
          code: 'CGB'
        }, {
          index: '99',
          name: '天津农村合作银行',
          code: 'TJRCB'
        }, {
          index: '100',
          name: '天津银行',
          code: 'TCCB'
        }, {
          index: '101',
          name: '徽商银行',
          code: 'HSB'
        }, {
          index: '102',
          name: '上海农村商业银行',
          code: 'SRCB'
        }, {
          index: '103',
          name: '北京农村商业银行',
          code: 'BJRCB'
        }, {
          index: '104',
          name: '江苏省农村信用社联合社',
          code: 'JSRCU'
        }, {
          index: '105',
          name: '宁波鄞州农村合作银行',
          code: 'BEEB'
        }, {
          index: '106',
          name: '安徽省农村信用联社',
          code: 'ARCU'
        }, {
          index: '107',
          name: '福建省农村信用社联合社',
          code: 'FJNX'
        }, {
          index: '108',
          name: '湖北省农村信用社联合社',
          code: 'HBNX'
        }, {
          index: '109',
          name: '深圳农村商业银行',
          code: 'SZRCB'
        }, {
          index: '110',
          name: '东莞农村商业银行',
          code: 'DRCB'
        }, {
          index: '111',
          name: '广西壮族自治区农村信用社联合社',
          code: 'GXNX'
        }, {
          index: '112',
          name: '海南省农村信用社联合社',
          code: 'HNNX'
        }, {
          index: '113',
          name: '云南省农村信用社联合社',
          code: 'YNRCC'
        }, {
          index: '114',
          name: '宁夏黄河农村商业银行',
          code: 'YRRCB'
        }, {
          index: '115',
          name: '外换银行',
          code: 'KEB'
        }, {
          index: '116',
          name: '新韩银行',
          code: 'XHB'
        }, {
          index: '117',
          name: '企业银行',
          code: 'IBK'
        }, {
          index: '118',
          name: '韩亚银行',
          code: 'HYB'
        }, {
          index: '119',
          name: '河北银行',
          code: 'HEBB'
        }, {
          index: '120',
          name: '邯郸市商业银行',
          code: 'BOHD'
        }, {
          index: '121',
          name: '珠海华润银行',
          code: 'CRBZ'
        }, {
          index: '122',
          name: '自贡市商业银行',
          code: 'ZGCCB'
        }, {
          index: '123',
          name: '广东南粤银行',
          code: 'GNB'
        }, {
          index: '124',
          name: '桂林银行',
          code: 'GLB'
        }, {
          index: '125',
          name: '吉林省农村信用社联合社',
          code: 'JLRCC'
        }, {
          index: '126',
          name: '嘉兴银行',
          code: 'JXB'
        }, {
          index: '127',
          name: '廊坊银行',
          code: 'LFB'
        }, {
          index: '128',
          name: '山东省农村信用社联合社',
          code: 'SDRCC'
        }, {
          index: '129',
          name: '友利银行',
          code: 'WBC'
        }, {
          index: '130',
          name: '长安银行',
          code: 'CAB'
        }, {
          index: '131',
          name: '浙江省农村信用社联合社',
          code: 'ZJRCC'
        }, {
          index: '132',
          name: '平顶山银行',
          code: 'PDSB'
        }, {
          index: '133',
          name: '北京顺义银座村镇银行',
          code: 'BSYZB'
        }, {
          index: '134',
          name: '广东华兴银行',
          code: 'GDHXB'
        }, {
          index: '135',
          name: '江西赣州银座村镇银行',
          code: 'JGYZB'
        }, {
          index: '136',
          name: '齐鲁银行',
          code: 'QLB'
        }, {
          index: '137',
          name: '深圳福田银座村镇银行',
          code: 'SFYZB'
        }, {
          index: '138',
          name: '浙江景宁银座村镇银行',
          code: 'ZJYZB'
        }, {
          index: '139',
          name: '浙江三门银座村镇银行',
          code: 'ZSYZB'
        }, {
          index: '140',
          name: '重庆黔江银座村镇银行',
          code: 'CQYZB'
        }, {
          index: '141',
          name: '重庆渝北银座村镇银行',
          code: 'CYYZB'
        }, {
          index: '142',
          name: '成都农商银行',
          code: 'CDRCB'
        }, {
          index: '143',
          name: '南充市商业银行',
          code: 'NCCCB'
        }, {
          index: '144',
          name: '成都银行',
          code: 'BOCD1'
        }, {
          index: '145',
          name: '盛京银行',
          code: 'SJB'
        }, {
          index: '146',
          name: '江苏长江商业银行',
          code: 'CJCCB'
        }, {
          index: '147',
          name: '泉州银行',
          code: 'QZCCB'
        }, {
          index: '148',
          name: '湖北银行',
          code: 'HBC'
        }, {
          index: '149',
          name: '江苏江阴农村商业银行',
          code: 'JRCB'
        }, {
          index: '150',
          name: '深圳前海微众银行',
          code: 'WEBANK'
        }, {
          index: '151',
          name: '武汉农村商业银行',
          code: 'WHRCB'
        }, {
          index: '152',
          name: '东亚银行',
          code: 'HKBEA'
        }, {
          index: '153',
          name: '衡水银行',
          code: 'HSBANK'
        }, {
          index: '154',
          name: '宁波通商银行',
          code: 'NCBANK'
        }, {
          index: '155',
          name: '九江银行',
          code: 'JJBANK'
        }, {
          index: '156',
          name: '枣庄银行',
          code: 'ZZB'
        }, {
          index: '157',
          name: '西安银行',
          code: 'XACB'
        }, {
          index: '158',
          name: '太仓农村商业银行',
          code: 'TCRCB'
        }, {
          index: '159',
          name: '海口联合农村商业银行',
          code: 'HKUB'
        }, {
          index: '160',
          name: '东营莱商村镇银行',
          code: 'DYLSB'
        }, {
          index: '161',
          name: '四川省农村信用社联合社',
          code: 'SCNX'
        }]
      }
    },
    mounted () {
      this.result = this.tableData
    },
    methods: {
      closeDialog () {
        console.log('ss')
        this.$emit('showOrHideDialog', false)
      },
      handleInput (e) {
        e.stopPropagation()
      },
      search (e) {
        e.stopPropagation()
        const searchResult = []
        const length = this.tableData.length
        for (let i = 0; i < length; i++) {
          if (this.tableData[i].name.indexOf(this.searchValue.toUpperCase()) > -1 || this.tableData[i].code.indexOf(this.searchValue.toUpperCase()) > -1) {
            searchResult.push(this.tableData[i])
          }
        }
        this.result = searchResult
      }
    },
    computed: {
      isVisible () {
        return this.bankVisible
      }
    }
  }
</script>
