// 跟单发货
export const UPDATE_DEDILIVER_CURRENT_TAB = 'UPDATE_DEDILIVER_CURRENT_TAB'
export const UPDATE_REJECT_CURRENT_TAB = 'UPDATE_REJECT_CURRENT_TAB'
export const UPDATE_BUYER_REJECT_CURRENT_TAB = 'UPDATE_BUYER_REJECT_CURRENT_TAB'
export const UPDATE_PARESSPAYDEBT_CURRENT_TAB = 'UPDATE_PARESSPAYDEBT_CURRENT_TAB'
